//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;Wch U20&quot;]
        ///[Site &quot;Kiljava&quot;]
        ///[Date &quot;1984.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;Anand, Viswanathan&quot;]
        ///[Black &quot;Wolff, Patrick G&quot;]
        ///[Result &quot;0-1&quot;]
        ///[WhiteElo &quot;2285&quot;]
        ///[BlackElo &quot;2225&quot;]
        ///[ECO &quot;B09&quot;]
        ///
        ///1.e4 d6 2.d4 Nf6 3.Nc3 g6 4.f4 Bg7 5.Nf3 O-O 6.e5 Nfd7 7.h4 c5 8.e6 fxe6
        ///9.h5 gxh5 10.Rxh5 Nf6 11.Rh4 Nc6 12.Be3 Qa5 13.Bd3 cxd4 14.Nxd4 Nxd4 15.Bxd4 e5
        ///16.fxe5 dxe5 17.Be3 e4 18.Bc4+ Kh8 19.Qd4 Bg4 20.Bb3 Rac8 21.Bd2 Qa6 22.Qe3 Nd5  0-1
        ///
        ///[Event &quot;Lloyds Bank op&quot;]
        ///[Site &quot;London&quot;]
        ///[Date &quot;1984.??.??&quot;]
        ///[Round  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Anand {
            get {
                return ResourceManager.GetString("Anand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;Olympiad URS&quot;]
        ///[Site &quot;Moscow (Russia)&quot;]
        ///[Date &quot;1979.??.??&quot;]
        ///[Round &quot;5&quot;]
        ///[White &quot;Akopian Vladimir (ARM)&quot;]
        ///[Black &quot;Golovey Tamara O (BLR)&quot;]
        ///[Result &quot;1/2-1/2&quot;]
        ///[ECO &quot;E66&quot;]
        ///[PlyCount &quot;53&quot;]
        ///
        ///1. d4 g6 2. c4 Bg7 3. Nf3 Nf6 4. g3 O-O 5. Bg2 d6 6. O-O Nc6 7. Nc3 a6 8. d5
        ///Na5 9. Nd2 c5 10. Qc2 Rb8 11. b3 b5 12. Bb2 e5 13. e4 Bh6 14. f4 Ng4 15. Rae1
        ///exf4 16. gxf4 bxc4 17. bxc4 Bg7 18. h3 Bd4+ 19. Kh1 Ne3 20. Rxe3 Bxe3 21. Ncb1
        ///Qh4 22. f5 Bf4 23. Nf3 Qg3 24. Bc3 Nxc4 25. Be1 Qxg2+ 26. Qxg2 Ne3 27.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string campioni {
            get {
                return ResourceManager.GetString("campioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;Wch U16&quot;]
        ///[Site &quot;Wattignies&quot;]
        ///[Date &quot;1976.08.27&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;Chandler, Murray G&quot;]
        ///[Black &quot;Kasparov, Gary&quot;]
        ///[Result &quot;1-0&quot;]
        ///[WhiteElo &quot;&quot;]
        ///[BlackElo &quot;&quot;]
        ///[ECO &quot;B22&quot;]
        ///
        ///1.e4 c5 2.c3 Nf6 3.e5 Nd5 4.d4 Nc6 5.Nf3 cxd4 6.cxd4 e6 7.a3 d6 8.Bd3 Qa5+
        ///9.Bd2 Qb6 10.Nc3 Nxc3 11.Bxc3 dxe5 12.dxe5 Be7 13.O-O Bd7 14.Nd2 Qc7 15.Qg4 O-O-O
        ///16.Rfc1 Kb8 17.Qc4 Rc8 18.b4 f6 19.Nf3 Qb6 20.Qe4 f5 21.Qe1 a6 22.Rab1 g5
        ///23.Nd2 Nd4 24.Qe3 Rxc3 25.Rxc3 f4 26.Qe1 g4 27.Ne4 Bc6 28.Nc5 Ka7 29.a4 Bf3
        ///30.a5 Qd8  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Kasparov {
            get {
                return ResourceManager.GetString("Kasparov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;Lloyds Bank op&quot;]
        ///[Site &quot;London&quot;]
        ///[Date &quot;1984.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Adams, Michael&quot;]
        ///[Black &quot;Sedgwick, David&quot;]
        ///[Result &quot;1-0&quot;]
        ///[WhiteElo &quot;&quot;]
        ///[BlackElo &quot;&quot;]
        ///[ECO &quot;C05&quot;]
        ///
        ///1.e4 e6 2.d4 d5 3.Nd2 Nf6 4.e5 Nfd7 5.f4 c5 6.c3 Nc6 7.Ndf3 cxd4 8.cxd4 f6
        ///9.Bd3 Bb4+ 10.Bd2 Qb6 11.Ne2 fxe5 12.fxe5 O-O 13.a3 Be7 14.Qc2 Rxf3 15.gxf3 Nxd4
        ///16.Nxd4 Qxd4 17.O-O-O Nxe5 18.Bxh7+ Kh8 19.Kb1 Qh4 20.Bc3 Bf6 21.f4 Nc4 22.Bxf6 Qxf6
        ///23.Bd3 b5 24.Qe2 Bd7 25.Rhg1 Be8 26.Rde1 Bf7 27.Rg3 Rc8 28.Reg1 Nd6 29.Rxg7 N [rest of string was truncated]&quot;;.
        /// </summary>
        public static string partite {
            get {
                return ResourceManager.GetString("partite", resourceCulture);
            }
        }
    }
}
